script: bundle exec rake build
rvm:
- ruby-2.3.7
- ruby-2.4.4
- ruby-2.5.1
- ruby-head
- jruby-head
deploy:
  matrix:
  - provider: rubygems
    gemspec: gem-bootstrap.gemspec
    skip_cleanup: true
    api_key:
      secure: p3mpEecKX1rkCiSVnItz47Rq7ZjUblq6+4HdzhHABOrpsqM+rdLXn9vsSwMQRHlN56wVMEDImh4w6njhi0yxk5CwiIhOWo96TjhIAh3FixUxCSM6yQFN/+VXSimfVzW+r3UDlpGyQ0h+j+Xkb6AWTg+FUOgk/bwGkBXbWFvxw9DcWbdmLm6VTGFJRVG/MA1pRPDxVja3/IFQAHRV4MZ4nJNfIfFO9ZyPS1PkObebB8yJRDi7keQ5LrLmq8kY3waaLfp9mNI2kkOBR3c7V+CyMAWg1tI0y5TRtZp63JxY26EcbJ2uu2Z9uoyAWEf5fzMkjQkhrL1EXY5n2tNc+qow3NS9FbqcoD8fVRcEYQGtKRafTkMXm+aCvCu95PbJ/r1UHb7qZJDradVRsgaS0klsd6Krted+UQVAGsBXszR/I9M0cQr7jrHr3NfIh1vBusKwVsqqCPD7dI2b3H4eN265QMPqvfWpzOpRRcVPKj07Frp4+vFwX1wCmNrgGXc5JCOSfrnKYSHWLoUn7LotElEX2DXLikOS3gp8ZybnKU0eOGyo0KsnGIYWDRJPM5nG8AVKH9tCQN+QAtyu/4qwzHER+tLJivnakJUGDU+tT8Dk8IyR9iiBc6I9JO+PufJBJX7SAQ7schb/fHUikjpn077GiwYu9oGvq3pmCNbsQedo338=
    on:
      ruby: ruby-2.5.1
      branch: master
      tags: true
  - provider: releases
    skip_cleanup: true
    fileglob: true
    file:
    - docs.tgz
    - gem-bootstrap-*.gem
    api_key:
      secure: gDDPfGed5Ue5xi06CH6IFaVE+MVRe/ZdQJ+TbrX66a8ah9HtTnlEOGhUl5KuGgMo9aTpKjTIoFKgXk/TQGW45Hu883C1xPMedSuBVv5E/W72bCbpYzcFuohWxwFdC+kbzyPUNIMne64D7skheJie3Pv8dmAGf1wxtfBbLOxthOlquDKtDgpXrcTMjayI47TnQj3YN0YLGppe9CyhST/CshBbTvJPjmOBpkoVcIShhXBO2OfJ+nhmHBPtd//pZRySRzTFRlgC9SSjKSYBWlgKvdG/cRUiz2Ez8r9rKk8idIOJCIJRMDLutCoVMvWm0jtI4/6IfIhZnIElUltAaVpNRSIJn/ibxcECnIEOGL5vZSPWszvWx0uuR/O7uTot2fhPeByAvxRoz75YiZtvquy5fWzQ7pu4BtdFd5WeCwqjw8ahBUrvPXqMOgIjlGvSSJEe3LGKG6V8PXCv35gqHOwO8/hsJM42Dr/CvpNV1NnS7zDKhFLk6mF/hBXtnJno6EMnSEiW26k1t3YvlcIq242KIp8iVNqcji6/h/W7llXG5clVE2ZCwdKeGySEfdawgOkXb/me2EE2HYMe/SSa15bhdJtYebkGA1GrQ3124S7nXshsFh61dA0sy85c55Y/kTbIlMv8fIbLOJ5oxAgc8TESaus8YZYBKYemVnvNZoxbOKk=
    on:
      ruby: ruby-2.5.1
      repo: theincognitocoder/gem-bootstrap
      branch: master
      tags: true
